"""Voice bridge — connects RALPH System 2 to pure-chat-llm voice interface.

The voice bridge enables:
1. Injecting RALPH insights into the voice agent's context
2. Receiving voice queries and routing to RALPH loop
3. Background System 2 analysis while user converses

Pure-chat-llm communicates via Obsidian plugin settings.
We inject context by writing to a vault note that the voice agent references.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from typing import Any

import httpx

logger = logging.getLogger("ralph.voice_bridge")

# Vault path for System 2 context injection
CONTEXT_NOTE = "_system2/current-context.md"
INSIGHTS_NOTE = "_system2/insights-buffer.md"


class VoiceBridge:
    """Bridge between RALPH System 2 and the voice interface."""

    def __init__(
        self,
        obsidian_api: str = "http://localhost:3000",
        vault: str = "gkg",
    ):
        self.api = obsidian_api
        self.vault = vault
        self._http: httpx.AsyncClient | None = None
        self._insight_buffer: list[dict[str, Any]] = []

    @property
    def http(self) -> httpx.AsyncClient:
        if self._http is None:
            self._http = httpx.AsyncClient(timeout=30.0)
        return self._http

    async def inject_context(self, context: dict[str, Any]) -> None:
        """Write System 2 context into the vault for voice agent to reference.

        This creates/updates a markdown note with structured context that
        pure-chat-llm can reference in its system prompt.
        """
        content = self._format_context(context)
        try:
            await self.http.post(
                f"{self.api}/create",
                json={
                    "name": CONTEXT_NOTE,
                    "content": content,
                    "overwrite": True,
                },
            )
            logger.info(f"Injected context to {CONTEXT_NOTE}")
        except Exception as e:
            logger.error(f"Failed to inject context: {e}")

    async def buffer_insight(self, insight: dict[str, Any]) -> None:
        """Buffer a System 2 insight for the next voice interaction.

        Insights accumulate until the voice agent pulls them.
        """
        self._insight_buffer.append(insight)

        # Write buffered insights to vault
        content = self._format_insights(self._insight_buffer)
        try:
            await self.http.post(
                f"{self.api}/create",
                json={
                    "name": INSIGHTS_NOTE,
                    "content": content,
                    "overwrite": True,
                },
            )
        except Exception as e:
            logger.error(f"Failed to write insights: {e}")

    async def flush_insights(self) -> list[dict[str, Any]]:
        """Return and clear the insight buffer."""
        insights = self._insight_buffer.copy()
        self._insight_buffer.clear()
        return insights

    def _format_context(self, context: dict[str, Any]) -> str:
        """Format context as a markdown note."""
        lines = [
            "---",
            "type: system2-context",
            f"updated: {self._now()}",
            "---",
            "",
            "# System 2 Context",
            "",
            "> Auto-generated by RALPH System 2. Referenced by voice agent.",
            "",
        ]

        if "graph_summary" in context:
            lines.append("## Graph State")
            lines.append(f"```json\n{json.dumps(context['graph_summary'], indent=2, default=str)[:1000]}\n```")
            lines.append("")

        if "active_query" in context:
            lines.append(f"## Active Query")
            lines.append(f"{context['active_query']}")
            lines.append("")

        if "traversal_path" in context:
            lines.append("## Suggested Reading Order")
            for i, node in enumerate(context["traversal_path"][:5], 1):
                lines.append(f"{i}. [[{node}]]")
            lines.append("")

        if "reflections" in context:
            lines.append("## Recent Reflections")
            for r in context["reflections"][-3:]:
                lines.append(f"- {r}")
            lines.append("")

        return "\n".join(lines)

    def _format_insights(self, insights: list[dict[str, Any]]) -> str:
        lines = [
            "---",
            "type: system2-insights",
            f"updated: {self._now()}",
            f"count: {len(insights)}",
            "---",
            "",
            "# System 2 Insights Buffer",
            "",
        ]

        for i, insight in enumerate(insights, 1):
            conf = insight.get("confidence", 0)
            lines.append(f"## Insight {i} (confidence: {conf:.2f})")
            lines.append(insight.get("text", str(insight)))
            if insight.get("evidence"):
                lines.append("Evidence:")
                for e in insight["evidence"]:
                    lines.append(f"  - [[{e}]]")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _now() -> str:
        from datetime import datetime, timezone
        return datetime.now(timezone.utc).isoformat()

    async def close(self):
        if self._http:
            await self._http.aclose()


def create_voice_system_prompt(vault: str = "gkg") -> str:
    """Create a vault-aware system prompt for the voice chat.

    This is injected into pure-chat-llm's OpenAI Realtime / Gemini Live config.
    It instructs the voice model to reference vault context.
    """
    return f"""You are a voice-activated knowledge assistant connected to a neurosymbolic vault.

You have access to a knowledge graph with 2557+ typed medical education notes:
- Learning Objectives (LOs) from ANZCA and CICM curricula
- SAQ exam questions with historical pass rates
- Index sections organizing the curriculum hierarchy
- Concepts linking cross-cutting medical themes

Behavior:
- When asked about a topic, reference specific LO codes (e.g., APE2i, C8iii)
- Cite pass rates when discussing exam-relevant topics
- Note when a topic has low pass rates (< 40%) — these are high-priority study areas
- Reference the System 2 context note at [[_system2/current-context]] for background analysis
- Check [[_system2/insights-buffer]] for recent deep-analysis insights

Style:
- Be concise and direct — this is voice, not text
- Use clinical precision in medical terminology
- Prioritize actionable study advice
- Say "I'm checking my graph analysis" when you need to reference context notes

Vault: {vault} | Types: lo, saq, index, concept, paper, task
"""
